### ISSUE TITLE
wget strip query strings in filenames

### ISSUE THREAD

**Issue by leonstafford** [Appish/appi.sh#2]
ie,  https://superuser.com/questions/61025/how-can-i-make-wget-rename-downloaded-files-to-not-include-the-query-string

as discussed in https://github.com/WP2Static/static-html-output-plugin/issues/83

**Comment by crechberger** [comment]
Hey,
I hope you are doing fine!
Any update on that issue?

**Comment by leonstafford** [comment]
@crechberger thanks for reminding me about this - working on it now. Have a few methods to strip the query string during post processing, just trying to find one that conforms to code quality checks

**Comment by leonstafford** [comment]
@crechberger couldn't get the perfect code implementation that doesn't produce warnings in `shellcheck`, but it's just a warning and Appish now strips the query strings correctly. If you want a small site to test on, `https://ljs.dev` is just a homepage at the moment, with some query strings within `assets/build/css` dir

**Comment by crechberger** [comment]
hey!
I'm not sure if the bugfix works. Appish still generates files with the name of "style.min.css?ver=7.6.1.css" for example

**Comment by crechberger** [comment]
you can try using my site as example, if it helps: https://blog-index.analytics-service.eu/

**Comment by leonstafford** [comment]
@crechberger checking now - it may have cached the request/not run with latest script

**Comment by leonstafford** [comment]
@crechberger looks like it was a caching issue, that I'll need to address in the script's 1-liner

Attached my results (used analytics.com as rewrite) - didn't see any query strings in expected filenames, let me know if there are any in particular in there:

[analyticscom.tar.gz](https://github.com/Appish/appi.sh/files/4798663/analyticscom.tar.gz)

**Comment by crechberger** [comment]
ok, thanks. Let me know once you added the 1 liner :)
