### ISSUE TITLE
Appish skips downloading webpage

### ISSUE THREAD

**Issue by crechberger** [Appish/appi.sh#8]
Hey,

So when using Appish, I created a new webpage on WordPress, but Appish doesn't download it. It's this one: (https://blog-index.analytics-service.eu/blog-1/). I really made sure that this wasn't about a caching issue, so can you try if that works on your end if this webpage gets downloaded.

Thank you for your help :)

**Comment by crechberger** [comment]
ah, well I think that's because on the whole website no link was pointing to it, so it's impossible for the crawler to get the page.

**Comment by leonstafford** [comment]
@crechberger - yep, that'll be it. With the WP plugins or how I imagine Sitecause works (they have a helper plugin for WP sites), is to detect all the main posts/page/archive URLs. That helps with things like landing pages, which may be orphaned/not crawlable from the site's root. 

You can force this without affecting your site if you add hidden, but valid links on the homepage or other page discoverable during crawling.

Appish should see some CLI argument support later, too, so you could link to local inclusion/exclusions files to force crawling of more paths.
